const c=document.getElementById('c'),ctx=c.getContext('2d'),tip=document.getElementById('tip');
const $=id=>document.getElementById(id);let W,H,DPR=1,mode='free',step=0,exercise=false,drag=null,why=true;
const controls=['rx','ry','rz','aux','fold','rays','folds','traces','construct','compare','measure'];controls.forEach(id=>$(id).addEventListener('input',draw));
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelector('.tabs .active').classList.remove('active');b.classList.add('active');mode=b.dataset.mode; preset(mode); draw();});
$('reset').onclick=()=>{rx.value=32;ry.value=-28;rz.value=18;aux.value=36;fold.value=110;mode='free';step=0;exercise=false;document.querySelector('.tabs .active').classList.remove('active');document.querySelector('[data-mode=free]').classList.add('active');draw()};
$('step').onclick=()=>{step=(step+1)%5; $('explain').textContent=['Step 1: establish HP and VP reference planes, then project all plane vertices to plan and elevation.','Step 2: find the edge view by choosing an auxiliary projector parallel to the plane normal.','Step 3: fold distances from the reference line into the auxiliary view.','Step 4: rotate the auxiliary plane parallel to the given plane to reveal true shape.','Step 5: compare true length edges, traces and dihedral angle readouts.'][step];draw()};
$('why').onclick=()=>{why=!why;$('why').textContent='Why this view: '+(why?'ON':'OFF');draw()};
$('exercise').onclick=()=>{exercise=!exercise;$('exercise').textContent=exercise?'Exercise: click likely true-shape view':'Exercise: predict true shape';$('explain').textContent=exercise?'Prediction task: adjust the auxiliary plane until the green “TRUE SHAPE” indicator appears, then click in the auxiliary viewport.':'Rotate the auxiliary plane until it becomes parallel to the inclined plane: the auxiliary view then reveals true shape.';draw()};
function resize(){DPR=devicePixelRatio||1;W=c.clientWidth;H=c.clientHeight;c.width=W*DPR;c.height=H*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);draw()}addEventListener('resize',resize);resize();
function V(x,y,z){return{x,y,z}}function add(a,b){return V(a.x+b.x,a.y+b.y,a.z+b.z)}function sub(a,b){return V(a.x-b.x,a.y-b.y,a.z-b.z)}function mul(a,s){return V(a.x*s,a.y*s,a.z*s)}function dot(a,b){return a.x*b.x+a.y*b.y+a.z*b.z}function cross(a,b){return V(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x)}function len(a){return Math.hypot(a.x,a.y,a.z)}function norm(a){let l=len(a)||1;return mul(a,1/l)}function rot(p,ax,ay,az){let x=p.x,y=p.y,z=p.z,c=Math.cos,s=Math.sin;let A=ax*Math.PI/180,B=ay*Math.PI/180,G=az*Math.PI/180;let y1=y*c(A)-z*s(A),z1=y*s(A)+z*c(A);y=y1;z=z1;let x1=x*c(B)+z*s(B),z2=-x*s(B)+z*c(B);x=x1;z=z2;let x2=x*c(G)-y*s(G),y2=x*s(G)+y*c(G);return V(x2,y2,z)}
function plane(){let ax=+rx.value,ay=+ry.value,az=+rz.value;if(mode=='edge'){ax=70;ay=0;az=20}else if(mode=='true'){ax=35;ay=-38;az=18}else if(mode=='intersect'){ax=42;ay=-20;az=25}let base=[V(-1.4,0,-.9),V(1.2,0,-.8),V(1.55,0,.65),V(-.85,0,1.05)];let pts=base.map(p=>add(rot(p,ax,ay,az),V(0,.25,0)));let n=norm(cross(sub(pts[1],pts[0]),sub(pts[2],pts[0])));return{pts,n,ax,ay,az}}
function auxBasis(){let a=+aux.value*Math.PI/180;let u=norm(V(Math.cos(a),0,Math.sin(a)));let v=V(0,1,0);let n=norm(cross(u,v));return{u,v,n,a}}
function proj3(p,rect){let S=Math.min(rect.w,rect.h)*.16,ca=Math.cos(-.65),sa=Math.sin(-.65),cb=Math.cos(.75),sb=Math.sin(.75);let x=p.x*ca-p.z*sa,z=p.x*sa+p.z*ca,y=p.y;let yy=y*cb-z*sb;return{x:rect.x+rect.w*.52+x*S,y:rect.y+rect.h*.58-yy*S}}
function project2(p,type,rect){let s=Math.min(rect.w,rect.h)*.16, x,y;if(type=='plan'){x=p.x;y=p.z}else if(type=='elev'){x=p.x;y=p.y}else if(type=='profile'){x=p.z;y=p.y}else{let b=auxBasis();x=dot(p,b.u);y=dot(p,b.v)}return{x:rect.x+rect.w/2+x*s,y:rect.y+rect.h/2-y*s}}
function line(a,b,col='#8fbff8',w=1,dash=[]){ctx.save();ctx.strokeStyle=col;ctx.lineWidth=w;ctx.setLineDash(dash);ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.restore()}function poly(ps,fill,stroke='#d9e4f5'){ctx.beginPath();ps.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill()}ctx.strokeStyle=stroke;ctx.lineWidth=1.5;ctx.stroke()}function txt(t,x,y,col='#b8c8dc',size=13){ctx.fillStyle=col;ctx.font=`${size}px ui-monospace,Consolas,monospace`;ctx.fillText(t,x,y)}function dotp(p,col='#fff',r=3){ctx.fillStyle=col;ctx.beginPath();ctx.arc(p.x,p.y,r,0,7);ctx.fill()}
function grid(r){ctx.strokeStyle='#223040';ctx.lineWidth=1;for(let x=r.x;x<r.x+r.w;x+=32)line({x,y:r.y},{x,y:r.y+r.h},'#1d2a38');for(let y=r.y;y<r.y+r.h;y+=32)line({x:r.x,y},{x:r.x+r.w,y},'#1d2a38');line({x:r.x,y:r.y+r.h/2},{x:r.x+r.w,y:r.y+r.h/2},'#405061',1.4);line({x:r.x+r.w/2,y:r.y},{x:r.x+r.w/2,y:r.y+r.h},'#405061',1.4)}
function draw(){ctx.clearRect(0,0,W,H);let left={x:0,y:0,w:W*.5,h:H*.5},ortho={x:W*.5,y:0,w:W*.5,h:H*.5},auxr={x:0,y:H*.5,w:W,h:H*.5};[left,ortho,auxr].forEach(grid);line({x:W*.5,y:0},{x:W*.5,y:H*.5},'#2d3948');line({x:0,y:H*.5},{x:W,y:H*.5},'#2d3948');let P=plane(),pts=P.pts;draw3D(left,P);drawOrtho(ortho,P);drawAux(auxr,P);drawReadout(P);}
function draw3D(r,P){txt('HP ground plane',r.x+20,r.y+r.h-20,'#6caef0');txt('VP vertical plane',r.x+20,r.y+34,'#6caef0');let o=proj3(V(0,0,0),r),x=proj3(V(2.8,0,0),r),z=proj3(V(0,0,2.8),r),y=proj3(V(0,2.2,0),r);line(o,x,'#5baefb',1.4);line(o,z,'#5baefb',1.4);line(o,y,'#7ad796',1.4);let ps=P.pts.map(p=>proj3(p,r));poly(ps,'rgba(233,210,94,.13)','#e6edf8');ps.forEach((p,i)=>{dotp(p);txt('ABCD'[i],p.x+5,p.y-5)});let cen=proj3(V(0,.25,0),r),normEnd=proj3(add(V(0,.25,0),mul(P.n,.9)),r);line(cen,normEnd,'#75d69a',2);txt('normal',normEnd.x+6,normEnd.y,'#75d69a');if($('rays').checked){ps.forEach(p=>line({x:r.x+r.w*.16,y:r.y+r.h*.22},p,'#69b7ff',.8,[5,5]));dotp({x:r.x+r.w*.16,y:r.y+r.h*.22},'#ffb25f',5);txt('projectors',r.x+r.w*.16+8,r.y+r.h*.22,'#ffb25f')}if(mode=='intersect'){let q=[V(-1,0,-1.1),V(1.1,0,-.9),V(1.25,0,.9),V(-1.05,0,.8)].map(p=>add(rot(p,-25,20,-18),V(.1,.05,.1)));poly(q.map(p=>proj3(p,r)),'rgba(189,133,255,.13)','#bd85ff');txt('second plane',r.x+r.w-160,r.y+45,'#bd85ff')}}
function drawOrtho(r,P){let gap=r.w/3;['PLAN','ELEVATION','PROFILE'].forEach((name,i)=>{let rr={x:r.x+i*gap,y:r.y,w:gap,h:r.h};txt(name,rr.x+16,rr.y+36,'#e8eef8',15);let type=['plan','elev','profile'][i],ps=P.pts.map(p=>project2(p,type,rr));poly(ps,'rgba(105,183,255,.08)','#dbe5f2');ps.forEach((p,j)=>dotp(p,j==0?'#fff':'#b7c7da',3));if($('construct').checked)ps.forEach(p=>line({x:p.x,y:rr.y+rr.h*.08},{x:p.x,y:rr.y+rr.h*.92},'#334658',.7,[4,6]));});if($('traces').checked){txt('horizontal trace',r.x+18,r.y+r.h-24,'#e9d25e');line({x:r.x+10,y:r.y+r.h-40},{x:r.x+r.w-10,y:r.y+r.h-40},'#e9d25e',1.5);txt('vertical trace',r.x+r.w*.56,r.y+62,'#75d69a');line({x:r.x+r.w*.55,y:r.y+50},{x:r.x+r.w*.55,y:r.y+r.h-25},'#75d69a',1.5)}}
function drawAux(r,P){txt('auxiliary reference / fold line',r.x+24,r.y+34,'#e9d25e');line({x:r.x+20,y:r.y+50},{x:r.x+r.w-20,y:r.y+50},'#e9d25e',1.5);let ar={x:r.x+30,y:r.y+60,w:r.w-60,h:r.h-80};let ps=P.pts.map(p=>project2(p,'aux',ar));let trueShape=Math.abs(dot(P.n,auxBasis().n))>.96;let edgeView=Math.abs(dot(P.n,auxBasis().n))<.08;let col=trueShape?'#75d69a':edgeView?'#ffb25f':'#e6edf8';poly(ps,trueShape?'rgba(117,214,154,.13)':'rgba(233,210,94,.08)',col);ps.forEach((p,i)=>{dotp(p,col,3);txt('ABCD'[i],p.x+5,p.y-5,col)});if($('folds').checked){P.pts.forEach((p,i)=>{let plan=project2(p,'plan',{x:ar.x,y:ar.y,w:ar.w,h:ar.h});line(plan,ps[i],'#69b7ff',.75,[3,5])})}if($('compare').checked){let wrong=ps.map((p,i)=>({x:p.x+34+(i%2)*20,y:p.y-26}));poly(wrong,'rgba(255,93,104,.07)','#ff5d68');txt('incorrect auxiliary transfer',wrong[0].x+20,wrong[0].y-20,'#ff5d68')}let label=trueShape?'TRUE SHAPE ACHIEVED':edgeView?'EDGE VIEW CONDITION':'AUXILIARY VIEW';txt(label,r.x+r.w-270,r.y+34,trueShape?'#75d69a':edgeView?'#ffb25f':'#b8c8dc',15);if(edgeView){let a=ps[0],b=ps[2];line(a,b,'#ffb25f',4);txt('plane collapses to an edge view',a.x+20,a.y+25,'#ffb25f')}let e=sub(P.pts[1],P.pts[0]),pointView=Math.abs(dot(norm(e),auxBasis().n))>.95;if(pointView){dotp(ps[0],'#ff5d68',7);txt('edge AB is in point view',ps[0].x+12,ps[0].y+16,'#ff5d68')}if($('measure').checked){let incHP=Math.acos(Math.min(1,Math.abs(dot(P.n,V(0,1,0)))))*180/Math.PI;let dih=Math.acos(Math.min(1,Math.abs(dot(P.n,auxBasis().n))))*180/Math.PI;txt(`inclination to HP: ${incHP.toFixed(1)}°`,r.x+24,r.y+r.h-44,'#b8c8dc');txt(`auxiliary dihedral: ${dih.toFixed(1)}°`,r.x+300,r.y+r.h-44,'#b8c8dc');txt(`shortest distance from point to plane: ${(Math.abs(dot(P.n,V(.8,.9,-.2))-dot(P.n,P.pts[0]))).toFixed(2)} units`,r.x+590,r.y+r.h-44,'#b8c8dc')}if(exercise){txt(trueShape?'Correct: auxiliary view shows true shape.':'Not yet: rotate auxiliary angle until the true-shape indicator appears.',r.x+24,r.y+r.h-20,trueShape?'#75d69a':'#ff5d68')}}
function drawReadout(P){if(!why)return;let b=auxBasis(),trueShape=Math.abs(dot(P.n,b.n))>.96,edgeView=Math.abs(dot(P.n,b.n))<.08;let s=trueShape?'Auxiliary plane is parallel to the given plane, so projected distances are not foreshortened.':edgeView?'The line of sight is nearly parallel to the plane surface, so the plane appears as a single edge.':'Auxiliary view is oblique: rotate the auxiliary plane to test edge view and true shape conditions.';$('explain').textContent=s}
function preset(m){if(m=='edge'){aux.value=-10;rx.value=70;ry.value=0;rz.value=20}else if(m=='true'){rx.value=35;ry.value=-38;rz.value=18;aux.value=52}else if(m=='intersect'){rx.value=42;ry.value=-20;rz.value=25;aux.value=30}}
c.addEventListener('mousemove',e=>{if(!why)return;tip.style.display='block';tip.style.left=e.clientX+14+'px';tip.style.top=e.clientY+14+'px';tip.textContent='Construction line: transfers perpendicular distance across a fold/reference line into an auxiliary projection.'});c.addEventListener('mouseleave',()=>tip.style.display='none');c.addEventListener('click',()=>{if(exercise){let P=plane(),ok=Math.abs(dot(P.n,auxBasis().n))>.96;$('explain').textContent=ok?'Correct diagnosis: the auxiliary projection now gives the true shape of the plane.':'Error diagnosis: this auxiliary view is still foreshortened. Align the auxiliary plane parallel to the given plane.'}});
